### ISSUE TITLE
Native support for scientific notation

### ISSUE THREAD

**Issue by Bykiev** [sebastienros/parlot#106]
Hi, it'll be helpful if scientific notation will be supported by Parlot out of the box. Some samples:

```
1.22e1
1e2
1e-2
1e+2 
```

**Comment by sebastienros** [comment]
`DecimalLiteral` already accepts a `NumberOptions` argument so we should just have to add more options, like the ones in [NumberStyles](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles?view=net-8.0). Only the options that make sense.

We could also have a `Parser.Number<T>(NumberStyles)` parser that would take these options and return the required type (decimal, double, int, ...). All C# numeric types have a Parse method to use internally, with different `NumberStyles` default (we would have the same mapping). Also think about using the ROS overload for it. Parlot would just need to match the pattern with the allowed chars and then use T.Parse().

Ultimately based on the chars that were found the Parse calls could be optimized. For instance if a single numeric char is found we can return the values based on ASCII mapping. Or if no `e` or signs were found these could be removed from the options in Parse such that it won't try to account for it.

**Comment by hishamco** [comment]
+1 for `NumberStyles`

**Comment by Bykiev** [comment]
> `DecimalLiteral` already accepts a `NumberOptions` argument so we should just have to add more options, like the ones in [NumberStyles](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles?view=net-8.0). Only the options that make sense.
> 
> We could also have a `Parser.Number<T>(NumberStyles)` parser that would take these options and return the required type (decimal, double, int, ...). All C# numeric types have a Parse method to use internally, with different `NumberStyles` default (we would have the same mapping). Also think about using the ROS overload for it. Parlot would just need to match the pattern with the allowed chars and then use T.Parse().
> 
> Ultimately based on the chars that were found the Parse calls could be optimized. For instance if a single numeric char is found we can return the values based on ASCII mapping. Or if no `e` or signs were found these could be removed from the options in Parse such that it won't try to account for it.

Sounds good, it'll be good to implement both of them

**Comment by sebastienros** [comment]
https://en.wikipedia.org/wiki/Decimal_separator

Explains how decimal numbers can be formatted. Extending on that the parser could take decimal marks and group separators as arguments.
