### ISSUE TITLE
Parlot 0.27 breaks Fluid.Core 2.10

### ISSUE THREAD

**Issue by Jojoshua** [sebastienros/parlot#114]
Something about Method not found when instantiating a new FluidParser

**Comment by sebastienros** [comment]
Fluid needs to be updated to use the latest and fix that. I don't think you can just replace parlot version with Fluid around.

**Comment by Jojoshua** [comment]
Ok, so maybe pin the version of Parlot in Fluid.core dependencies. Right now it's >=.25

**Comment by lahma** [comment]
I'd say it's better to think Parlot as transitive dependency when using Fluid and let nuget handle the default resolution without explicitly referencing Parlot.

**Comment by Jojoshua** [comment]
Whatever you decide is fine and close the issue whenever. I'm just reverting to .25 for now

**Comment by deanebarker** [comment]
Same problem, same solution -- downgrading to 0.25 fixes it.

**Comment by gumbarros** [comment]
> Something about Method not found when instantiating a new FluidParser

`System.MissingMethodException: Method not found: 'Parlot.Fluent.Parser`1 Parlot.Fluent.Parsers.AndSkip(Parlot.Fluent.Parser`1, Parlot.Fluent.Parser`1)'. at Fluid.FluidParser..ctor(FluidParserOptions parserOptions) at Fluid.FluidParser..ctor() at JJMasterData.Core.UI.Components.JJFormView.GetHtmlTemplateActionResult() in /home/gumbarros/RiderProjects/infinity/jjmasterdata/src/Core/UI/Components/FormView/JJFormView.cs:line 671 at JJMasterData.Core.UI.Components.JJFormView.GetFormActionResult() in /home/gumbarros/RiderProjects/infinity/jjmasterdata/src/Core/UI/Components/FormView/JJFormView.cs:line 625 at JJMasterData.Core.UI.Components.JJFormView.GetFormResultAsync() in /home/gumbarros/RiderProjects/infinity/jjmasterdata/src/Core/UI/Components/FormView/JJFormView.cs:line 465 at JJMasterData.Core.UI.Components.JJFormView.BuildResultAsync() in /home/gumbarros/RiderProjects/infinity/jjmasterdata/src/Core/UI/Components/FormView/JJFormView.cs:line 394 at JJMasterData.Core.UI.Components.AsyncComponent.GetResultAsync() in /home/gumbarros/RiderProjects/infinity/jjmasterdata/src/Core/UI/Components/AsyncComponent.cs:line 15 at JJMasterData.Web.Areas.MasterData.Controllers.FormController.Render(String elementName) in /home/gumbarros/RiderProjects/infinity/jjmasterdata/src/Web/Areas/MasterData/Controllers/FormController.cs:line 22 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Logged|12_1(ControllerActionInvoker invoker) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Logged|17_1(ResourceInvoker invoker) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)`

I'm getting the same exception installing NCalc and Fluid at the same project.

**Comment by gumbarros** [comment]
I think this issue can be closed, because Fluid needs to be updated at Nuget.org to use Parlot 0.28 and fix the transitive dependency conflict.

(https://github.com/sebastienros/fluid/issues/677)
