### ISSUE TITLE
Terms.Integer() is not parsing the leading negative sign

### ISSUE THREAD

**Issue by deanebarker** [sebastienros/parlot#133]
v0.0.28

The built-in `Terms.Interger()` is not parsing negatives:

```
Terms.Integer().Parse("123")    // 123
Terms.Integer().Parse("-123")   // 0
```

The doc specifically states:

>Matches an integral numeric value and an optional leading sign.

I don't think I have to specify anything, because I traced the `Integer` parser back to the enum `NumberOptions.Integer`, which is:

```
Integer = AllowLeadingSign
```

**Comment by sebastienros** [comment]
I updated the documentation recently due to these changes:
https://github.com/sebastienros/parlot/pull/132

However the nuget package is not up to date with that version of the code.

**Comment by sebastienros** [comment]
I'd like to finish some work I started on compilers before shipping a new major version (1.0). The goal is to stop shipping patch version updates that are breaking, people a complaining because that breaks Fluid if they are using tools like dependabot that automatically updates these.
