### ISSUE TITLE
Should I have multiple parsers, or just one big one?

### ISSUE THREAD

**Issue by deanebarker** [sebastienros/parlot#134]
Best practice question --

If you look at this class, I have defined multiple parsers based on all the different commands that could be issued.

https://gist.github.com/deanebarker/befe90bc93a8d433cb4d7cc050592c95#file-conversationalvariablecollection-cs-L249

In that method specifically, I try every parser against the incoming command, and use the first one that returns something other than `null` (the first one that succeeds, basically).

Question: I could technically roll all these parsers into one big parser using `OneOf` (I'd have to equalize the return value, but I could work that out).  Is this the "right" way to do it? Or is my model of "try every parser serially until one matches" a valid methodology?

**Comment by sebastienros** [comment]
All these `if (parserX.Parse()...` are equivalent to a `OneOf<T>` parser or `p1.Or(p2).Or(p3)`.

> I'd have to equalize the return value

Which you are already doing returning `string`. With only parser combinations this would be in `Then()` statements.

An advantage of `OneOf` over only doing manually is that `OneOf` can create a lookup table (if all subsequent parsers have this possibility) and it won't be a set of ifs, but something more direct: "oh, the next char is a digit, so this can only be the `Integer()`, and if it's not that then let's not try the others".

**Comment by deanebarker** [comment]
I'm actually returning four different things.

```
private readonly Parser<VariableOperation> executeCommandParser;
private readonly Parser<VariableComparison> checkValueParser;
private readonly Parser<string> retrieveValueParser;
private readonly Parser<VariableExistence> checkExistenceQuestionParser;
private readonly Parser<VariableExistence> checkExistenceDeclarationParser;
private readonly Parser<string> removeParser;
private readonly Parser<VariableOperation> adjustParser;
```

Could I have an interface on all of them, and do something like this?

```
var command = (ICommand)OneOf(parser1, parser2, parser3).Parse(commandText);

if(command is VariableOperation)
  DoThis(command)

if(command is VariableExistence)
  DoSomethingElse(command)

...
```

Essentially, saying "parse this into whatever you can, then I'll figure out what that is and take the right action."

**Comment by sebastienros** [comment]
You can return an interface, right, and then each class you return would have the `Do()` implementation. Then you don't need to do another set of ifs, just invoke `result.Do()` and whatever you return will "do" it ;)

If you don't want to return an interface to make things more straightforward, there in an implicit way in C#, returning an `Action<X, Y>` (x, y if you need arguments), like this:

```
var actionToDoParser = OneOf<Action>(
    Terms.Integer().Then(x => () => DoThisWithAnInteger(x)),
    Terms.Text("show").Then(x => () => DoThat()),
    ...);

var actionToDo = actionToDoParser.Parse(input);
actionToDo?.Invoke(); // Execute the "lambda" that was returned
```

**Comment by deanebarker** [comment]
Sure enough, this works. But is it a good practice?

```csharp
void Main()
{
  var word = Terms.NonWhiteSpace().Then(s => (IParserResult)new Word() { Value = s.ToString() });
  var number = Terms.Integer().Then(s => (IParserResult)new Number() { Value = s});

  var main = OneOf(number, word);  // This always returns IParserResult

  var result = main.Parse("deane");
	
  if(result is Number)
    "This is a Number!".Dump();

  if (result is Word)
    "This is a Word!".Dump();
}

public interface IParserResult { }

public class Number : IParserResult
{
	public long Value { get; set; }
}

public class Word : IParserResult
{
	public string Value { get; set; }
}
```

**Comment by sebastienros** [comment]
The good practice would be to have a `Dump()` method on the interface, not check with `is` every possible implementation. 

```c#
void Main()
{
  var word = Terms.NonWhiteSpace().Then(s => (IParserResult)new Word() { Value = s.ToString() });
  var number = Terms.Integer().Then(s => (IParserResult)new Number() { Value = s});

  var main = OneOf(number, word);  // This always returns IParserResult

  var result = main.Parse("deane");
  result.Dump();	
}

public interface IParserResult 
{
    void Dump();
}

public class Number : IParserResult
{
    public long Value { get; set; }
    
    public void Dump() => Console.WriteLine($"Number: {Value}");
}

public class Word : IParserResult
{
    public string Value { get; set; }
	
    public void Dump() => Console.WriteLine($"Word: {Value}");}
```

**Comment by deanebarker** [comment]
Yeah, that makes sense.

What I'm really parsing is a "command," whatever form it exists in. So I created `ICommand` with an `Execute` method. Now `OneOf` knows that an `ICommand` is coming out of _one_ of its internal parsers, then I just check that it's not null, and call `Execute` on it.

Code is much cleaner now. I assume it's also faster.

Thanks.
