### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/parlot#147]
AFAIR there was a regression with the compilation refactoring and the usage of `ISeekable` in [this PR](https://github.com/sebastienros/parlot/pull/138) but I was able to mitigate it.

Nonetheless, there seem to be a significant regression, even on `Raw` benchmark which don't involve the Fluent API and Parser objects.

Parlot 0.0.19

```
BenchmarkDotNet v0.13.10, Windows 11 (10.0.22631.3155/23H2/2023Update/SunValley3)
12th Gen Intel Core i7-1260P, 1 CPU, 16 logical and 12 physical cores
.NET SDK 8.0.200
  [Host]   : .NET 8.0.2 (8.0.224.6711), X64 RyuJIT AVX2
  ShortRun : .NET 8.0.2 (8.0.224.6711), X64 RyuJIT AVX2

Job=ShortRun  IterationCount=3  LaunchCount=1
WarmupCount=3

| Method              | Mean        | Error       | StdDev    | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|-------------------- |------------:|------------:|----------:|------:|--------:|-------:|----------:|------------:|
| ParlotRawSmall      |    176.1 ns |    41.63 ns |   2.28 ns |  0.60 |    0.00 | 0.0322 |     304 B |        0.46 |
| ParlotCompiledSmall |    292.4 ns |    43.69 ns |   2.39 ns |  1.00 |    0.00 | 0.0696 |     656 B |        1.00 |
| ParlotFluentSmall   |    360.3 ns |    44.18 ns |   2.42 ns |  1.23 |    0.01 | 0.0696 |     656 B |        1.00 |
| PidginSmall         |  5,237.3 ns | 2,162.97 ns | 118.56 ns | 17.91 |    0.33 | 0.0839 |     832 B |        1.27 |
|                     |             |             |           |       |         |        |           |             |
| ParlotRawBig        |    846.2 ns |   106.47 ns |   5.84 ns |  0.55 |    0.00 | 0.1268 |    1200 B |        0.42 |
| ParlotCompiledBig   |  1,551.9 ns |   274.97 ns |  15.07 ns |  1.00 |    0.00 | 0.3052 |    2888 B |        1.00 |
| ParlotFluentBig     |  1,921.7 ns |   116.32 ns |   6.38 ns |  1.24 |    0.01 | 0.3052 |    2888 B |        1.00 |
| PidginBig           | 26,802.7 ns | 6,253.70 ns | 342.79 ns | 17.27 |    0.09 | 0.4272 |    4152 B |        1.44 |
```

Parlot 1.0.2

```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.22631.3880/23H2/2023Update/SunValley3)
12th Gen Intel Core i7-1260P, 1 CPU, 16 logical and 12 physical cores
.NET SDK 9.0.100-rc.1.24406.16
  [Host]   : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2
  ShortRun : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX2

Job=ShortRun  IterationCount=3  LaunchCount=1
WarmupCount=3

| Method              | Mean        | Error       | StdDev    | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|-------------------- |------------:|------------:|----------:|------:|--------:|-------:|----------:|------------:|
| ParlotRawSmall      |    203.2 ns |   106.15 ns |   5.82 ns |  0.44 |    0.01 | 0.0322 |     304 B |        0.44 |
| ParlotCompiledSmall |    460.2 ns |   161.17 ns |   8.83 ns |  1.00 |    0.02 | 0.0730 |     688 B |        1.00 |
| ParlotFluentSmall   |    457.8 ns |    46.47 ns |   2.55 ns |  1.00 |    0.02 | 0.0730 |     688 B |        1.00 |
| PidginSmall         |  5,344.7 ns |   640.95 ns |  35.13 ns | 11.62 |    0.21 | 0.0839 |     832 B |        1.21 |
|                     |             |             |           |       |         |        |           |             |
| ParlotRawBig        |  1,072.5 ns |   665.56 ns |  36.48 ns |  0.41 |    0.02 | 0.1259 |    1200 B |        0.39 |
| ParlotCompiledBig   |  2,647.2 ns | 1,591.34 ns |  87.23 ns |  1.00 |    0.04 | 0.3242 |    3080 B |        1.00 |
| ParlotFluentBig     |  2,365.0 ns |   256.98 ns |  14.09 ns |  0.89 |    0.03 | 0.3242 |    3080 B |        1.00 |
| PidginBig           | 28,341.4 ns | 9,588.06 ns | 525.55 ns | 10.71 |    0.36 | 0.4272 |    4152 B |        1.35 |
```

**Comment by Bykiev** [comment]
Actually, it's just a nanoseconds, so, it's not a significant regression. If the code with a new codebase is more readable and supportable I'd say leave it as is

**Comment by lahma** [comment]
Well nanoseconds can matter if it's a large percentual difference 😉 Might be worth to test both branches with latest benchmarkdotnet and maybe without `ShortRun` and let benchmarkdotnet choose the testing plan (iterations).

**Comment by sebastienros** [comment]
|                     |          |          |        |
|---------------------|----------|----------|--------|
| ParlotRawSmall      | 176.10   | 203.20   | 15.39% |
| ParlotCompiledSmall | 292.40   | 460.20   | 57.39% |
| ParlotFluentSmall   | 360.30   | 457.80   | 27.06% |
| PidginSmall         | 5237.30  | 5344.70  | 2.05%  |
|                     |          |          |        |
| ParlotRawBig        | 846.20   | 1072.50  | 26.74% |
| ParlotCompiledBig   | 1551.90  | 2647.20  | 70.58% |
| ParlotFluentBig     | 1921.70  | 2365.00  | 23.07% |
| PidginBig           | 26802.70 | 28341.40 | 5.74%  |

**Comment by sebastienros** [comment]
> EDIT: the SDKs and and runtimes are also different so a lot of moving parts...

I agree, knew that, but I put Pidgin here as a baseline.

**Comment by sebastienros** [comment]
> I agree, knew that, but I put Pidgin here as a baseline.

But you are right still, there will always be a doubt if not on par. Will re-run to remove this variable.

**Comment by sebastienros** [comment]
Ran it on fixed machine dedicated for benchmarking with a more recent processor

```
BenchmarkDotNet v0.14.0, Debian GNU/Linux 12 (bookworm) (container)
Intel Xeon E-2336 CPU 2.90GHz, 1 CPU, 12 logical and 6 physical cores
.NET SDK 8.0.303
  [Host]   : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  ShortRun : .NET 8.0.7 (8.0.724.31311), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

Job=ShortRun  IterationCount=3  LaunchCount=1
WarmupCount=3
```

**v0.0.19**

```
| Method              | Mean        | Error       | StdDev   | Ratio | RatioSD | Gen 0  | Allocated |
|---------------------|-------------|-------------|----------|-------|---------|--------|-----------|
| ParlotRawSmall      | 307.0 ns    | 10.22 ns    | 0.56 ns  | 0.64  | 0       | 0.0496 | 312 B     |
| ParlotCompiledSmall | 478.3 ns    | 19.30 ns    | 1.06 ns  | 1     | 0       | 0.1049 | 664 B     |
| ParlotFluentSmall   | 740.9 ns    | 23.99 ns    | 1.32 ns  | 1.55  | 0       | 0.1049 | 664 B     |
| PidginSmall         | 6,348.5 ns  | 90.53 ns    | 4.96 ns  | 13.27 | 0.02    | 0.1297 | 832 B     |
|                     |             |             |          |       |         |        |           |
| ParlotRawBig        | 1,537.0 ns  | 13.75 ns    | 0.75 ns  | 0.61  | 0       | 0.1907 | 1,208 B   |
| ParlotCompiledBig   | 2,523.9 ns  | 72.36 ns    | 3.97 ns  | 1     | 0       | 0.4616 | 2,896 B   |
| ParlotFluentBig     | 3,920.6 ns  | 79.62 ns    | 4.36 ns  | 1.55  | 0       | 0.4578 | 2,896 B   |
| PidginBig           | 33,119.1 ns | 1,360.48 ns | 74.57 ns | 13.12 | 0.04    | 0.6104 | 4,152 B   |

**v0.0.28**

```
| Method              | Mean        | Error       | StdDev    | Ratio | RatioSD | Gen0   | Allocated |
|---------------------|-------------|-------------|-----------|-------|---------|--------|-----------|
| ParlotRawSmall      | 243.5 ns    | 10.67 ns    | 0.59 ns   | 0.45  | 0       | 0.0482 | 304 B     |
| ParlotCompiledSmall | 540.9 ns    | 13.64 ns    | 0.75 ns   | 1     | 0       | 0.1097 | 688 B     |
| ParlotFluentSmall   | 628.0 ns    | 11.64 ns    | 0.64 ns   | 1.16  | 0       | 0.1097 | 688 B     |
| PidginSmall         | 6,270.0 ns  | 397.08 ns   | 21.77 ns  | 11.59 | 0.04    | 0.1297 | 832 B     |
|                     |             |             |           |       |         |        |           |
| ParlotRawBig        | 1,246.2 ns  | 16.64 ns    | 0.91 ns   | 0.41  | 0       | 0.1907 | 1200 B    |
| ParlotCompiledBig   | 3,064.1 ns  | 179.58 ns   | 9.84 ns   | 1     | 0       | 0.4883 | 3080 B    |
| ParlotFluentBig     | 3,455.3 ns  | 95.81 ns    | 5.25 ns   | 1.13  | 0       | 0.4883 | 3080 B    |
| PidginBig           | 31,858.2 ns | 3,055.18 ns | 167.46 ns | 10.4  | 0.06    | 0.6104 | 4152 B    |
```

**v1.0.2**

```
| Method              | Mean        | Error     | StdDev   | Ratio | RatioSD | Gen0   | Allocated |
|---------------------|-------------|-----------|----------|-------|---------|--------|-----------|
| ParlotRawSmall      | 242.8 ns    | 8.15 ns   | 0.45 ns  | 0.44  | 0       | 0.0482 | 304 B     |
| ParlotCompiledSmall | 554.5 ns    | 10.47 ns  | 0.57 ns  | 1     | 0       | 0.1097 | 688 B     |
| ParlotFluentSmall   | 627.6 ns    | 20.55 ns  | 1.13 ns  | 1.13  | 0       | 0.1097 | 688 B     |
| PidginSmall         | 6,373.3 ns  | 140.06 ns | 7.68 ns  | 11.49 | 0.02    | 0.1297 | 832 B     |
|                     |             |           |          |       |         |        |           |
| ParlotRawBig        | 1,263.2 ns  | 32.10 ns  | 1.76 ns  | 0.4   | 0       | 0.1907 | 1200 B    |
| ParlotCompiledBig   | 3,147.8 ns  | 61.67 ns  | 3.38 ns  | 1     | 0       | 0.4883 | 3080 B    |
| ParlotFluentBig     | 3,434.4 ns  | 81.82 ns  | 4.48 ns  | 1.09  | 0       | 0.4883 | 3080 B    |
| PidginBig           | 32,396.1 ns | 289.55 ns | 15.87 ns | 10.29 | 0.01    | 0.6104 | 4152 B    |
```

What surprises me is that the allocations are the same. But the output rightly showed the different BenchmarkDotNet versions (13.1, 13.2 and 14.0) so I am confident the correct branches were benchmarked.

If you want me to run other specific forks/branches feel free to point them to me.

Note for myself:

```
crank --config C:\temp\parlot.yml --profile aspnet-perf-lin --scenario ExprBench --json parlot.v0.0.28.json --application.source.branchOrCommit v0.0.28
```

**Comment by lahma** [comment]
Am I reading this correctly, no actual performance regression?

**Comment by sebastienros** [comment]
@lahma this is what I am reading too.
