### ISSUE TITLE
Capture parser

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/parlot#23]
To return the TextSpan of a complex pattern, without caring about each individual part.
Pattern matching.

**Comment by sebastienros** [comment]
Can just bookmark the start when the pattern is starting, and return the textspan once the parser is successful.

**Comment by Ellested** [comment]
I've just noticed this library, and it looks super awesome. I took it for a spin, bit I had some problems trying to catch literal text, and didn't figure a way to do it. Is this comment about a way to handle that specific issue?
I was actually looking into making a new Parser class to accept input until a specific pattern was found, as I couldn't construct one from the current set. Other than that I really like the way this is put together, I think your'e a genius :-)

**Comment by sebastienros** [comment]
Thanks for your comment.

It took me a few minutes to understand what I meant with this issue so I will rephrase it.

The Capture parser accepts a parser as an argument and returns the textspan that is matched by this argument. The idea is that if you look for a pattern but don't care about each matched element, it will discard the internal state of the argument parser and return where it started or finished.

The implementation should be trivial, like 4 lines of code:
- mark the start
- call the argument parser
- if parser is not successful reset position to start
- if parser is successful return textspan from start and current position

This inherits from Parser<Textspan>

I mentioned it's like pattern matching because in the end you just get where the pattern was found and not each sub token that matched.

**Comment by Ellested** [comment]
Thanks for replying so fast :-)

OK, is it currently possible to match anything until a specific char/pattern?
I tried with something like OneOrMore(Not(Char('x'))) - or something along that.., but I didn't really succeed. I wanted to see if I could build a HTML parser, and the idea was to parse everything as Text nodes, that doesn't qualify as tags, attributes and comments (etc.). Is a scenario like that currently supported with the built-in set of parsers, or do I need to make a new custom parser class?

**Comment by deanmarcussen** [comment]
You might be looking for `AnyCharBefore(Pattern(c => c != 'x'))`, but more likely `AnyCharBefore(TagsParser)` where `TagsParser` is a collection of parsers that match your known properties.

**Comment by Ellested** [comment]
Thanks dean, exactly what I'm looking for.

**Comment by Ellested** [comment]
Well, all of you contributors can multiply the "genius" factor by 5 😀
The HTML parser is almost complete, and I've spend days in other libraries. I will have to do some manual token parsing (tag matching), unless I realize another way. But this is an awesome library, so clean and simple to use. Fantastic job 👍
