### ISSUE TITLE
Q: Analog to Boost.Spirit genre embedded parsers

### ISSUE THREAD

**Issue by mwpowellhtx** [sebastienros/parlot#50]
Hello, sir, compelling work. Is it analog to Boost.Spirit vis-a-vis embedded parsers, DSL's, etc? Thanks, cheers... Vive la France; for your LIBERTIES there in France. GODSPEED.

**Comment by sebastienros** [comment]
Just discovered this project, and yes I think it's the same logic, i.e. parser combinators, which means parsers are built as composites of smaller parsers. I am sure I can learn from it.

**Comment by mwpowellhtx** [comment]
Yes, I am coming from a `Boost.Spirit` background, although not so much with `X3`, YMMV. Also, with experience with `ANTLR`, but I think that is code generated based on the spec, not quite the same thing; closer to a traditional `YACC`, etc.

**Comment by sebastienros** [comment]
I also have some experience with antlr, but from a long time ago. And I helped someone re-implement an antlr grammar recently:

![image](https://user-images.githubusercontent.com/1165805/136277918-04fa31e6-1296-47f5-be2e-9addcc3c5e3c.png)

**Comment by mwpowellhtx** [comment]
Wow, performance pushing 10x, an order of magnitude. Impressive.
