### ISSUE TITLE
Documentation should make it clear that NumberOptions needs to be set to AllowSign in order to parse negative values

### ISSUE THREAD

**Issue by pmarflee** [sebastienros/parlot#87]
The [Integer](https://github.com/sebastienros/parlot/blob/main/docs/parsers.md#integer) and [Decimal](https://github.com/sebastienros/parlot/blob/main/docs/parsers.md#decimal) examples in the documentation are incorrect. They give the impression that `Terms.Integer()` and `Terms.Decimal()` will successfully parse negative values. However, parsing negative values requires `NumberOptions` to be set to `AllowSign`, e.g. `Terms.Integer(NumberOptions.AllowSign)`.

**Comment by hishamco** [comment]
Please submit a PR

**Comment by sebastienros** [comment]
I'll check the source to be sure it's intentional. Seems weird. Might be a bug more than a lack of documentation.

**Comment by sebastienros** [comment]
I fixed the documentation, this was intentional.
