### ISSUE TITLE
Parsing multiline strings

### ISSUE THREAD

**Issue by pmarflee** [sebastienros/parlot#88]
Why does the following code:

```
var input = 
    $"""
    .....
    .F-7.
    .|.|.
    .L-J.
    .....
    """;

var parser = Separated(
    Terms.Text(Environment.NewLine),
    OneOrMany(
        OneOf(Terms.Char('|'),
            Terms.Char('-'),
            Terms.Char('L'),
            Terms.Char('J'),
            Terms.Char('7'),
            Terms.Char('F'),
            Terms.Char('.'),
            Terms.Char('S'))));
    
var result = parser.Parse(input);
```

produce a singleton List containing 25 entries, instead of 5x lists each containing 5 entries?

Or should I be parsing multiline strings in a different way?

**Comment by sebastienros** [comment]
`Terms` will [implicitly accept spaces](https://github.com/sebastienros/parlot/blob/main/docs/parsers.md#terms-and-literals) so the new lines will be part of the "Char" result. Try to use `Literals.Char` instead.

**Comment by pmarflee** [comment]
Changing the separator parser from `Terms.Text(Environment.NewLine)` to `Literals.Text(Environment.NewLine)` still returns a singleton list with 25 elements. Should this not work?

Changing the separator parser to `Literals.Char('\r').And(Literals.Char('\n'))` (I'm using Windows as my primary OS) also produces the same result. Furthermore, it's a bit of a hassle to have to create a Char parser from `Environment.NewLine`. Why can't I use `Literals.Text` instead?

**Comment by pmarflee** [comment]
Please ignore my last comment. I figured it out. The following code produces the desired result:

```
var input = 
    $"""
    .....
    .F-7.
    .|.|.
    .L-J.
    .....
    """;

var parser = Separated(
    Literals.Text(Environment.NewLine),
    OneOrMany(
        OneOf(Literals.Char('|'),
            Literals.Char('-'),
            Literals.Char('L'),
            Literals.Char('J'),
            Literals.Char('7'),
            Literals.Char('F'),
            Literals.Char('.'),
            Literals.Char('S'))));
    
var result = parser.Parse(input);
```

**Comment by sebastienros** [comment]
I tried locally and I believe there is a bug in `OneOf`, currently investigating.
:
Note that if you want the parsers to not skip whitespaces there is another option by using 

```
var parseContext = new ParseContext(new Scanner(input), true);
var result = parser.Parse(parseContext);
```

Though this should probably be made easier to access on `Parse()` directly.
